default[:meetme_newrelic_plugin][:postgresql][:host] = 'localhost'
default[:meetme_newrelic_plugin][:postgresql][:port] = '5432'
default[:meetme_newrelic_plugin][:postgresql][:user] = 'postgres'
default[:meetme_newrelic_plugin][:postgresql][:password] = 'postgres'
default[:meetme_newrelic_plugin][:postgresql][:dbname] = 'postgres'
default[:meetme_newrelic_plugin][:postgresql][:superuser] = 'False'
default[:meetme_newrelic_plugin][:postgresql][:relation_stats] = 'True'
